local H = require("tests/harness")
local LRU = require("wildwise/core/lru")
local Lifetime = require("wildwise/core/lifetime")
local Hooks = require("wildwise/core/hooks")
local P = require("wildwise/core/protocol")
local Config = require("wildwise/core/config")
local json = require("cjson")
H.test("LRU evicts least recently read entity", function()
    local lru = LRU.new(2); lru:set("a", 1); lru:set("b", 2); H.eq(lru:get("a"), 1)
    lru:set("c", 3); H.eq(lru:peek("b"), nil); H.eq(lru.size, 2)
    lru:remove("a"); lru:set("c", 4); H.eq(lru:get("c"), 4); H.eq(lru.size, 1)
end)
H.test("LRU stays bounded across 10000 entities", function()
    local lru = LRU.new(256)
    for i = 1, 10000 do lru:set(i, i) end
    H.eq(lru.size, 256); lru:clear(); H.eq(lru.first, nil); H.eq(lru.size, 0)
end)
H.test("lifetime releases listeners and tasks once", function()
    local e, scope, calls = H.entity(1), Lifetime.new(), 0
    scope:listen(e, "event", function() calls = calls + 1 end)
    scope:task({ Cancel = function() calls = calls + 10 end })
    e:PushEvent("event"); scope:close(); scope:close(); e:PushEvent("event"); H.eq(calls, 11)
end)
H.test("hooks preserve nil returns and later wrappers", function()
    local object, scope = { method = function(_, x) return x, nil, 3 end }, Lifetime.new()
    Hooks.after(scope, object, "method", function() end)
    local first = object.method
    object.method = function(...) return first(...) end
    local a, b, c = object:method(7); H.eq(a, 7); H.eq(b, nil); H.eq(c, 3)
    scope:close(); a, b, c = object:method(9); H.eq(a, 9); H.eq(b, nil); H.eq(c, 3)
end)
H.test("protocol round trip carries version session and fields", function()
    local bytes = assert(P.encode(json, "delta", "session-1", 2, { fields = { health = 7 }, removed = {} }))
    local msg = assert(P.decode(json, bytes)); H.eq(msg.v, 1); H.eq(msg.data.fields.health, 7)
end)
H.test("protocol rejects executable cyclic nonfinite oversized payloads", function()
    H.eq(P.encode(json, "x", "s", 1, { fn = function() end }), nil)
    H.eq(P.encode(json, "x", "s", 1, { n = 0 / 0 }), nil)
    local cycle = {}; cycle.self = cycle
    H.eq(P.encode(json, "x", "s", 1, cycle), nil)
    H.eq(P.decode(json, string.rep("x", 12001)), nil)
    H.eq(P.decode(json, '{"v":2,"session":"x","seq":1,"kind":"x","data":{}}'), nil)
end)
H.test("rate budget resists bursts and reverse clock", function()
    local bucket = P.bucket(2, 3, 0)
    assert(P.allow(bucket, 0, 3)); H.eq(P.allow(bucket, 0), false)
    assert(P.allow(bucket, .5)); H.eq(P.allow(bucket, -.5), false); H.eq(P.allow(bucket, .5), false)
end)
H.test("diff sends deletion rather than false zero", function()
    local changed, removed = P.diff({ health = 7, armor = 5 }, { health = 6 })
    H.eq(changed.health, 6); H.eq(changed.armor, nil); H.eq(removed[1], "armor")
end)
H.test("conservative defaults and mode policies", function()
    local config = Config.load(function() end)
    H.eq(config.pickup_allowed, false); H.eq(config.stack_manual, false); H.eq(config.stack_loaded, false)
    local positions, exploration = Config.share(config, "survival", false); assert(positions and exploration)
    positions, exploration = Config.share(config, "wilderness", false); assert(not positions and not exploration)
    positions, exploration = Config.share(config, "survival", true); assert(not positions and not exploration)
end)
H.test("conflicts disable only overlapping modules using workshop IDs", function()
    local config = Config.load(function() end)
    local reasons = Config.compat(config, { "workshop-1595631294", "workshop-2477889104", "geometric placement" })
    H.eq(config.signs, false); H.eq(config.beefalo, false); H.eq(config.queue, true); assert(reasons.signs)
end)
H.test("modinfo loads in the real restricted shape", function()
    local chunk = assert(loadfile("modinfo.lua")); local env = { locale = "zh" }; setfenv(chunk, env); chunk()
    assert(env.all_clients_require_mod and not env.client_only_mod); assert(#env.configuration_options > 20)
end)
