local M = {}
M.text = {
    no_points = { "No aligned points in selection", "区域内没有对齐的点位" },
    clear_all = { "Clear everyone's markers (admin)", "清空所有人的标记（管理员）" },
    ["beefalo.hunger_threshold"] = { "Beefalo hunger threshold", "牛饥饿显示阈值" },
    found = { "Found", "找到" },
    info = { "Information", "信息" },
    maps = { "Map", "地图" },
    items = { "Items", "物品" },
    queue = { "Queue", "队列" },
    diagnostics = { "Diagnostics", "诊断" },
    close = { "Close", "关闭" },
    on = { "On", "开启" },
    off = { "Off", "关闭" },
    yes = { "Yes", "是" },
    no = { "No", "否" },
    health = { "Health", "生命" },
    health_max = { "Max health", "最大生命" },
    damage = { "Base damage", "基础伤害" },
    planar_damage = { "Planar damage", "位面伤害" },
    planar_defense = { "Planar defense", "位面防御" },
    armor = { "Armor", "护甲耐久" },
    absorption = { "Protection", "减伤" },
    attack_range = { "Attack range", "攻击范围" },
    frozen = { "Frozen", "冻结" },
    burning = { "Burning", "燃烧中" },
    food_health = { "Health from food", "食用生命" },
    food_hunger = { "Hunger from food", "食用饥饿" },
    food_sanity = { "Sanity from food", "食用理智" },
    edible = { "Can eat", "可以食用" },
    food_type = { "Food type", "食物类型" },
    freshness = { "Freshness", "新鲜度" },
    perish_time = { "Base spoilage budget (not ETA)", "基础腐败余量（非倒计时）" },
    ingredients = { "Ingredients", "食材属性" },
    durability = { "Durability", "耐久" },
    uses = { "Uses", "剩余次数" },
    uses_max = { "Max uses", "总次数" },
    waterproof = { "Waterproof", "防水" },
    insulation = { "Insulation", "保温" },
    insulation_type = { "Insulation type", "保温类型" },
    speed = { "Speed multiplier", "速度倍率" },
    dapperness = { "Sanity / s", "理智／秒" },
    fuel = { "Fuel %", "燃料百分比" },
    fuel_time = { "Fuel time", "燃料时间" },
    fuel_value = { "Fuel value", "燃料量" },
    cook_time = { "Cooking", "烹饪剩余" },
    dry_time = { "Drying", "晾晒剩余" },
    growth_time = { "Growth", "生长剩余" },
    stage = { "Stage", "生长阶段" },
    harvest = { "Harvest", "可收获数量" },
    moisture = { "Soil is moist", "土壤湿润" },
    nutrients = { "Nutrients", "养分" },
    stress = { "Stress", "压力" },
    fertilizer = { "Fertilizer", "肥料效果" },
    leader = { "Leader", "主人" },
    loyalty = { "Loyalty", "忠诚剩余" },
    contents = { "Contents", "容器内容" },
    bundle = { "Bundle", "包裹内容" },
    count = { "Count", "数量" },
    domestication = { "Domestication", "驯化" },
    obedience = { "Obedience", "顺从" },
    hunger = { "Hunger", "饥饿" },
    hunger_max = { "Max hunger", "饥饿上限" },
    tendency = { "Tendency", "倾向" },
    domesticated = { "Domesticated", "已驯化" },
    ride_time = { "Ride time", "骑乘剩余" },
    saddle_uses = { "Saddle uses", "鞍具剩余次数" },
    saddle_name = { "Saddle", "鞍具" },
    season = { "Season", "季节" },
    season_days = { "Season days left", "本季剩余天数" },
    day = { "Day", "天数" },
    phase = { "Time of day", "时段" },
    temperature = { "Temperature", "温度" },
    wetness = { "World wetness", "世界湿度" },
    base_cook_time = { "base time", "基础耗时" },
    select_ping = { "Choose marker", "选择标记" },
    ["beefalo.layout"] = { "Mount panel layout", "牛栏布局" },
    ["beefalo.background"] = { "Mount background opacity", "牛栏背景不透明度" },
    badges = { "Native badges", "原生徽章" },
    compact = { "Compact text", "紧凑文字" },
    toggle_sign = { "Toggle this container's sign (session)", "显示／隐藏此箱木牌（本次运行）" },
    hover_sign_target = {
        "Hover a nearby supported container before opening F7",
        "先指向附近受支持容器，再按 F7",
    },
    sign_hidden = { "This container's sign is hidden for this session", "此箱木牌已隐藏，本次运行有效" },
    sign_shown = { "This container's sign is shown", "此箱木牌已显示" },
    hunger_rate = { "Hunger / s", "饥饿／秒" },
    sanity_rate = { "Sanity rate", "理智变化率" },
    world_events = { "World events", "世界事件" },
    healthbars = { "Combat bars", "战斗血条" },
    signs = { "Smart storage signs", "智能小木牌" },
    beefalo = { "Beefalo status", "牛状态栏" },
    ["info.preset"] = { "Information preset", "信息预设" },
    minimal = { "Minimal", "简洁" },
    standard = { "Standard", "标准" },
    detailed = { "Detailed", "详细" },
    ["healthbars.limit"] = { "Bar limit", "血条上限" },
    ["healthbars.scale"] = { "Bar scale", "血条缩放" },
    ["healthbars.numbers"] = { "Health numbers", "血量数值" },
    ["info.font_size"] = { "Font size", "字号" },
    ui_scale = { "Interface scale", "界面缩放" },
    ["healthbars.hostile_scope"] = { "Hostility scope", "敌意范围" },
    self = { "Self", "仅自己" },
    followers = { "Self and followers", "自己及随从" },
    nearby = { "Nearby players", "附近玩家" },
    nearby_followers = { "Players and followers", "附近玩家及随从" },
    ["map.share_position"] = { "Share my position", "共享我的位置" },
    ["map.share_exploration"] = { "Share exploration", "共享探索" },
    ["map.indicators"] = { "Off-screen indicators", "屏外指示" },
    scoreboard = { "Player list only", "查看玩家列表时" },
    always = { "Always", "始终显示" },
    ["items.pickup"] = { "Auto pickup", "自动拾取" },
    ["items.stack_world"] = { "Stack new drops", "新掉落合堆" },
    ["items.stack_manual"] = { "Stack manual drops", "主动丢弃物合堆" },
    ["items.stack_loaded"] = { "Stack loaded items", "读档物品合堆" },
    ["info.container_contents"] = { "Container queries", "容器查询" },
    ["info.attack_range"] = { "Range hints", "范围提示" },
    paused = { "Paused", "已暂停" },
    running = { "Running", "执行中" },
    idle = { "Idle", "空闲" },
    pause = { "Pause", "暂停" },
    resume = { "Resume", "继续" },
    clear = { "Clear", "清空" },
    queue_limit = { "Queue limit reached", "已达到队列上限" },
    ping_limit = { "Five markers already active", "已存在五个标记" },
    invalid_ping = { "Invalid marker", "无效标记" },
    cancelled = { "Cancelled", "已取消" },
    manual_control = { "Manual control", "手动接管" },
    input_focus = { "Input focus changed; resume manually", "界面或窗口焦点变化，请手动继续" },
    death = { "Dead or ghost", "死亡或幽灵状态" },
    attacked = { "Attacked", "受到攻击" },
    ms_becameghost = { "Became a ghost", "进入幽灵状态" },
    ms_playerdespawnandmigrate = { "Changing shard", "正在切换世界" },
    disconnected = { "Waiting for server", "等待服务器" },
    unsupported_state = { "Action unavailable in this state", "当前状态不支持操作" },
    recipe_locked = { "Recipe not learned", "尚未解锁配方" },
    materials_empty = { "Materials exhausted", "材料耗尽" },
    tool_missing = { "No usable tool in inventory", "库存没有可用工具" },
    inventory_full = { "Inventory full", "背包已满" },
    timeout = { "No progress", "无进展" },
    action_failed = { "Action failed", "动作失败" },
    location = { "Location", "位置" },
    danger = { "Danger", "危险" },
    resource = { "Resource", "资源" },
    rally = { "Rally", "集合" },
    signal_fire = { "Signal fire", "信号火" },
    ["map.ping_kind"] = { "Alt + map click marker", "Alt＋地图点击标记" },
    ["queue.farm_grid"] = { "Farm grid", "农田布点" },
    server_rule = { "Server rule · restart to change", "服务器规则 · 修改后重启" },
    restricted = { "Disabled by server", "服务器未允许" },
    conflict = { "Overlapping mod enabled", "已启用重叠功能模组" },
    first_tip = {
        "Wildwise is ready. F7 opens settings. Shift-click queues actions.",
        "Wildwise 已就绪。F7 打开设置，Shift＋点击添加队列。",
    },
    unknown = { "Unavailable", "暂不可用" },
    default = { "Default", "默认" },
    rider = { "Rider", "行牛" },
    ornery = { "Ornery", "战牛" },
    pudgy = { "Pudgy", "肥牛" },
    execute_plan = { "Execute plan", "执行布点" },
    cancel_plan = { "Cancel preview", "取消预览" },
    enabled_points = { "Valid / total", "有效／总点数" },
    menu_key = { "Menu key", "菜单按键" },
    ["queue.modifier_key"] = { "Queue modifier", "队列修饰键" },
    ["beefalo.toggle_key"] = { "Beefalo toggle", "牛状态切换键" },
    rebind = { "Press a key…", "请按键…" },
    ["beefalo.visible"] = { "Show beefalo status", "显示牛状态" },
    ["beefalo.offset_x"] = { "Beefalo horizontal offset", "牛状态水平偏移" },
    ["beefalo.offset_y"] = { "Beefalo vertical offset", "牛状态垂直偏移" },
    auto = { "Follow game", "跟随游戏" },
    zh = { "简体中文", "简体中文" },
    en = { "English", "English" },
    recipes = { "Recipes using hovered food", "包含所选食材的料理" },
    find = { "Locate same item", "定位同类物品" },
    recipe_query = { "Four-ingredient recipe query", "四格食材料理查询" },
    cookpot = { "Crock Pot", "普通烹饪锅" },
    portablecookpot = { "Portable Crock Pot", "便携烹饪锅" },
    four_ingredients = { "Choose four ingredients", "请选择四格食材" },
    invalid_ingredient = { "Not a cooking ingredient", "不是有效烹饪食材" },
    invalid_recipe = {
        "Recipe data unavailable; preview cannot be verified",
        "配方数据异常，无法确认料理结果",
    },
    query_truncated = { "Search limit reached; move closer and retry", "查询达到上限，请靠近目标后重试" },
    wormholetravel = { "Wormhole travel; previous queue cleared", "经过虫洞，已清空原队列" },
    query = { "Query recipes", "查询料理" },
    more = { "More", "更多" },
    back = { "Back", "返回" },
    language = { "Language", "语言" },
    combat = { "Combat", "战斗" },
    food = { "Food", "食物" },
    equipment = { "Equipment", "装备" },
    progress = { "Timers", "加工进度" },
    farm = { "Farming", "农业" },
    follower = { "Followers", "随从" },
    container = { "Storage", "容器" },
    world = { "World", "世界" },
    ["info.categories"] = { "Information categories", "信息类别" },
}
M.text["beefalo.enabled"] = M.text.beefalo
M.text["healthbars.enabled"] = M.text.healthbars
M.text["info.enabled"] = M.text.info
M.text["items.enabled"] = M.text.items
M.text["map.enabled"] = M.text.maps
M.text["queue.enabled"] = M.text.queue
M.text["queue.limit"] = M.text.queue_limit
M.text["signs.enabled"] = M.text.signs
M.text["info.world_events"] = M.text.world_events
M.text.map = M.text.maps

-- 能力补齐的双语文案；具体字段不依赖服务器语言。
M.text["language"] = { "Language", "语言" }
M.text["ui_scale"] = { "Interface scale", "界面缩放" }
M.text["menu_key"] = { "Menu key", "菜单按键" }
M.text["diagnostics"] = { "Local diagnostic logs", "本地诊断日志" }
M.text["healthbars.linger_seconds"] = { "Out-of-combat delay", "脱战收起延迟" }
M.text["items.pickup_allowed"] = { "Allow opt-in auto pickup", "允许玩家开启自动拾取" }
M.text["items.pickup_existing"] = { "Pickup requires existing item", "拾取要求背包已有同类" }
M.text["items.radius"] = { "Item radius", "物品处理半径" }
M.text["signs.treasurechest"] = { "Signs on chests", "木箱小木牌" }
M.text["signs.dragonflychest"] = { "Signs on scaled chests", "龙鳞宝箱小木牌" }
M.text["signs.boat_ancient_container"] = { "Signs on cargo holds", "远古船货舱小木牌" }
M.text["signs.chester"] = { "Signs on Chester", "切斯特小木牌" }
M.text["signs.hutch"] = { "Signs on Hutch", "哈奇小木牌" }
M.text["signs.icebox"] = { "Signs on ice boxes", "冰箱小木牌" }
M.text["signs.saltbox"] = { "Signs on salt boxes", "盐盒小木牌" }
M.text["signs.fish_box"] = { "Signs on tin fishin' bins", "鱼类储物箱小木牌" }
M.text["info.combat"] = { "Combat numbers", "战斗数值" }
M.text["info.food_values"] = { "Food effects", "食物三维" }
M.text["info.perishable"] = { "Freshness and perish estimates", "鲜度与保鲜估时" }
M.text["info.equipment"] = { "Equipment details", "装备详情" }
M.text["info.progress"] = { "Processing and growth", "加工与生长" }
M.text["info.farm"] = { "Farm details", "农田详情" }
M.text["info.follower"] = { "Follower details", "随从详情" }
M.text["info.cooldowns"] = { "Recharge and cooldown", "充能与冷却" }
M.text["info.timers"] = { "Named entity timers", "已知实体计时器" }
M.text["info.max_lines"] = { "Normal information lines", "常规信息行数" }
M.text["info.inspect_lines"] = { "Inspection information lines", "检查信息行数" }
M.text["info.time_style"] = { "Time display", "时间格式" }
M.text["info.temperature_units"] = { "Temperature units", "温度单位" }
M.text["map.wormholes"] = { "Wormhole markers", "虫洞标记" }
M.text["map.pings"] = { "Allow map pings", "允许地图标记" }
M.text["map.signal_fires"] = { "Allow signal fires", "允许信号火" }
M.text["items.world_radius"] = { "World stacking radius", "世界掉落合堆半径" }
M.text["items.manual_radius"] = { "Manual stacking radius", "玩家丢弃合堆半径" }
M.text["items.pickup_radius"] = { "Auto pickup radius", "自动拾取半径" }
M.text["items.world_ash"] = { "World stacking: ash", "世界掉落合堆：灰烬" }
M.text["items.world_poop"] = { "World stacking: manure", "世界掉落合堆：粪便" }
M.text["items.world_seeds"] = { "World stacking: seeds", "世界掉落合堆：种子" }
M.text["items.manual_ash"] = { "Manual stacking: ash", "玩家丢弃合堆：灰烬" }
M.text["items.manual_poop"] = { "Manual stacking: manure", "玩家丢弃合堆：粪便" }
M.text["items.manual_seeds"] = { "Manual stacking: seeds", "玩家丢弃合堆：种子" }
M.text["items.pickup_ash"] = { "Auto pickup: ash", "自动拾取：灰烬" }
M.text["items.pickup_poop"] = { "Auto pickup: manure", "自动拾取：粪便" }
M.text["items.pickup_seeds"] = { "Auto pickup: seeds", "自动拾取：种子" }
M.text["queue.collect_after_work"] = { "Collect after work", "工作后收集" }
M.text["queue.double_click_speed"] = { "Double click interval", "双击间隔" }
M.text["queue.double_click_range"] = { "Double click radius", "双击同类半径" }
M.text["signs.bundle_contents"] = { "Show bundled contents on signs", "木牌显示包裹内容" }
M.text["signs.body_skins"] = { "Use stored mini sign skins", "使用箱中小木牌皮肤" }
M.text["signs.scale"] = { "Storage sign scale", "小木牌缩放" }
M.text["beefalo.show_hunger"] = { "Show mount hunger", "显示坐骑饥饿" }
M.text["beefalo.scale"] = { "Mount panel scale", "坐骑栏独立缩放" }
M.text["game_days"] = { "game days", "游戏天" }
M.text["inspect_more"] = { "… %d more; hold Inspect", "… 还有 %d 项，按住检查键展开" }
M.text["details_truncated"] =
    { "… %d more; increase inspection lines in F7", "… 还有 %d 项，可在 F7 增加检查行数" }
M.text["perish_estimate"] = { "Estimated spoilage time", "预计腐败时间" }
M.text["perish_state"] = { "Perish estimate basis", "保鲜估算状态" }
M.text["recharge"] = { "Charge", "充能" }
M.text["cooldown_time"] = { "Cooldown remaining", "冷却剩余" }
M.text["item_moisture"] = { "Item wetness", "物品湿度" }
M.text["item_temperature"] = { "Item temperature", "物品温度" }
M.text["sew_value"] = { "Sewing fuel restored", "缝补恢复量" }
M.text["repair_health"] = { "Repair health restored", "修复生命" }
M.text["repair_uses"] = { "Repair uses restored", "修复使用次数" }
M.text["repair_work"] = { "Repair work restored", "修复工作量" }
M.text["repair_freshness"] = { "Freshness restored", "恢复鲜度" }
M.text["repair_percent"] = { "Health fraction restored", "恢复生命比例" }
M.text["cook_product"] = { "Cooking product", "烹饪产物" }
M.text["dry_product"] = { "Drying product", "晾晒产物" }
M.text["process_state"] = { "Processing state", "加工状态" }
M.text["timers"] = { "Entity timers", "实体计时" }
M.text["stress_points"] = { "Accumulated stress", "累计压力" }
M.text["stress_max"] = { "Recorded maximum stress", "已记录最大压力" }
M.text["stress_sources"] = { "Recorded stage stressors", "本阶段已记录压力源" }
M.text["stress_none"] = { "None", "无" }
M.text["stress_nutrients"] = { "Nutrients", "养分" }
M.text["stress_moisture"] = { "Water", "水分" }
M.text["stress_killjoys"] = { "Weeds or debris", "杂草或杂物" }
M.text["stress_family"] = { "Same species nearby", "同种作物陪伴" }
M.text["stress_overcrowding"] = { "Overcrowding", "过度拥挤" }
M.text["stress_happiness"] = { "Tending", "照料" }
M.text["stress_season"] = { "Season", "季节" }
M.text["ready_to_harvest"] = { "Ready to harvest", "可收获" }
M.text["cooking"] = { "Cooking", "烹饪中" }
M.text["drying"] = { "Drying", "晾晒中" }
M.text["acid_rain"] = { "Acid rain; estimate unavailable", "酸雨额外腐败，暂不估算" }
M.text["custom_modifier"] = { "Custom modifier; estimate unavailable", "自定义倍率，暂不估算" }
M.text["freshening"] = { "Freshness recovering", "正在恢复鲜度" }
M.text["environment_estimate"] = { "Assumes current environment is unchanged", "假设当前环境保持不变" }
M.text["regrowth"] = { "Regrowth", "再生" }
M.text["cooldown"] = { "Cooldown", "冷却" }
M.text["decay"] = { "Decay", "自然消退" }
M.text["clock"] = { "Minutes:seconds", "分:秒" }
M.text["seconds"] = { "Seconds", "秒" }
M.text["days"] = { "Game days", "游戏天" }
M.text["both"] = { "Time and game days", "时间与游戏天" }
M.text["game"] = { "Game units", "游戏值" }
M.text["celsius"] = { "Celsius", "摄氏度" }
M.text["fahrenheit"] = { "Fahrenheit", "华氏度" }
M.text["map.show_players"] = { "Player map icons", "地图玩家图标" }
M.text["map.show_pings"] = { "Map pings", "地图标记" }
M.text["map.show_fires"] = { "Signal fire icons", "信号火图标" }
M.text["map.show_wormholes"] = { "Wormhole icons", "虫洞图标" }
M.text["map_controls"] = {
    "Alt+left: marker wheel; Alt+right: delete own marker",
    "Alt＋左键选择标记；Alt＋右键删除自己的标记",
}
M.text["items.world_filters"] = { "World stacking filters", "世界掉落合堆过滤" }
M.text["items.manual_filters"] = { "Manual stacking filters", "玩家丢弃合堆过滤" }
M.text["items.pickup_filters"] = { "Auto pickup filters", "自动拾取过滤" }
M.text["ash"] = { "Ash", "灰烬" }
M.text["poop"] = { "Manure", "粪便" }
M.text["seeds"] = { "Seeds", "种子" }
M.text["queue.last_recipe_key"] = { "Repeat last recipe key", "再次制作上次配方按键" }
M.text["bounded_farming"] = {
    "Shift+right drag: preview farm tiles, then confirm. One action per tile.",
    "Shift＋右键拖框预览农田，确认后每块执行一次。",
}
M.text["container_unavailable"] = { "Container unavailable or inaccessible", "容器暂不可用或无访问权限" }

-- 解析语言设置，auto 跟随游戏，未知语言回退英文。
function M.language(setting, G)
    if setting ~= "auto" then
        return setting
    end
    local code = G.LOC and G.LOC.GetLocaleCode() or "en"
    return code:sub(1, 2) == "zh" and "zh" or "en"
end

-- 读取双语文本，缺少词条时返回原键以便诊断。
function M.get(key, lang)
    local value = M.text[key]
    return value and value[lang == "zh" and 2 or 1] or tostring(key)
end
return M
