local M = {}
M.text = {
    no_points = { "No aligned points in selection", "区域内没有对齐的点位" },
    clear_all = { "Clear everyone's markers (admin)", "清空所有人的标记（管理员）" },
    hunger_threshold = { "Hunger display threshold", "饥饿显示阈值" },
    found = { "Found", "找到" },
    info = { "Information", "信息" }, maps = { "Map", "地图" }, items = { "Items", "物品" },
    queue = { "Queue", "队列" }, diagnostics = { "Diagnostics", "诊断" }, close = { "Close", "关闭" },
    on = { "On", "开启" }, off = { "Off", "关闭" }, yes = { "Yes", "是" }, no = { "No", "否" },
    health = { "Health", "生命" }, health_max = { "Max health", "最大生命" }, damage = { "Base damage", "基础伤害" },
    armor = { "Armor", "护甲耐久" }, absorption = { "Protection", "减伤" }, attack_range = { "Attack range", "攻击范围" },
    frozen = { "Frozen", "冻结" }, burning = { "Burning", "燃烧中" },
    food_health = { "Health from food", "食用生命" }, food_hunger = { "Hunger from food", "食用饥饿" },
    food_sanity = { "Sanity from food", "食用理智" }, edible = { "Can eat", "可以食用" }, food_type = { "Food type", "食物类型" },
    freshness = { "Freshness", "新鲜度" }, perish_time = { "Base perish time", "基础腐败时间" }, ingredients = { "Ingredients", "食材属性" },
    durability = { "Durability", "耐久" }, uses = { "Uses", "剩余次数" }, uses_max = { "Max uses", "总次数" },
    waterproof = { "Waterproof", "防水" }, insulation = { "Insulation", "保温" }, insulation_type = { "Insulation type", "保温类型" },
    speed = { "Speed multiplier", "速度倍率" }, dapperness = { "Sanity / s", "理智／秒" },
    fuel = { "Fuel %", "燃料百分比" }, fuel_time = { "Fuel time", "燃料时间" }, fuel_value = { "Fuel value", "燃料量" },
    cook_time = { "Cooking", "烹饪剩余" }, dry_time = { "Drying", "晾晒剩余" }, growth_time = { "Growth", "生长剩余" },
    stage = { "Stage", "生长阶段" }, harvest = { "Harvest", "可收获数量" }, moisture = { "Soil is moist", "土壤湿润" },
    nutrients = { "Nutrients", "养分" }, stress = { "Stress", "压力" }, fertilizer = { "Fertilizer", "肥料效果" },
    leader = { "Leader", "主人" }, loyalty = { "Loyalty", "忠诚剩余" }, contents = { "Contents", "容器内容" },
    bundle = { "Bundle", "包裹内容" }, count = { "Count", "数量" },
    domestication = { "Domestication", "驯化" }, obedience = { "Obedience", "顺从" }, hunger = { "Hunger", "饥饿" },
    hunger_max = { "Max hunger", "饥饿上限" }, tendency = { "Tendency", "倾向" }, domesticated = { "Domesticated", "已驯化" },
    ride_time = { "Ride time", "骑乘剩余" }, saddle_uses = { "Saddle uses", "鞍具剩余次数" },
    season = { "Season", "季节" }, season_days = { "Season days left", "本季剩余天数" }, day = { "Day", "天数" },
    phase = { "Time of day", "时段" }, temperature = { "Temperature", "温度" }, wetness = { "World wetness", "世界湿度" },
    naughtiness = { "Naughtiness", "淘气值" }, hunger_rate = { "Hunger / s", "饥饿／秒" }, sanity_rate = { "Sanity rate", "理智变化率" },
    world_events = { "World events", "世界事件" }, healthbars = { "Combat bars", "战斗血条" },
    signs = { "Smart storage signs", "智能小木牌" }, beefalo = { "Beefalo status", "牛状态栏" },
    preset = { "Information preset", "信息预设" }, minimal = { "Minimal", "简洁" }, standard = { "Standard", "标准" }, detailed = { "Detailed", "详细" },
    bar_limit = { "Bar limit", "血条上限" }, bar_scale = { "Bar scale", "血条缩放" }, bar_numbers = { "Health numbers", "血量数值" },
    font_size = { "Font size", "字号" }, ui_scale = { "Interface scale", "界面缩放" }, hostile_scope = { "Hostility scope", "敌意范围" },
    self = { "Self", "仅自己" }, followers = { "Self and followers", "自己及随从" }, nearby = { "Nearby players", "附近玩家" },
    nearby_followers = { "Players and followers", "附近玩家及随从" }, position = { "Share my position", "共享我的位置" },
    exploration = { "Share exploration", "共享探索" }, indicators = { "Off-screen indicators", "屏外指示" },
    scoreboard = { "Player list only", "查看玩家列表时" }, always = { "Always", "始终显示" },
    pickup = { "Auto pickup", "自动拾取" }, stack_world = { "Stack new drops", "新掉落合堆" }, stack_manual = { "Stack manual drops", "主动丢弃物合堆" },
    stack_loaded = { "Stack loaded items", "读档物品合堆" }, containers = { "Container queries", "容器查询" }, ranges = { "Range hints", "范围提示" },
    paused = { "Paused", "已暂停" }, running = { "Running", "执行中" }, idle = { "Idle", "空闲" },
    pause = { "Pause", "暂停" }, resume = { "Resume", "继续" }, clear = { "Clear", "清空" },
    queue_limit = { "Queue limit reached", "已达到队列上限" }, ping_limit = { "Five markers already active", "已存在五个标记" },
    invalid_ping = { "Invalid marker", "无效标记" }, cancelled = { "Cancelled", "已取消" },
    manual_control = { "Manual control", "手动接管" }, input_focus = { "Input focus changed; resume manually", "界面或窗口焦点变化，请手动继续" },
    death = { "Dead or ghost", "死亡或幽灵状态" }, attacked = { "Attacked", "受到攻击" },
    ms_becameghost = { "Became a ghost", "进入幽灵状态" }, ms_playerdespawnandmigrate = { "Changing shard", "正在切换世界" },
    disconnected = { "Waiting for server", "等待服务器" }, unsupported_state = { "Action unavailable in this state", "当前状态不支持操作" },
    recipe_locked = { "Recipe not learned", "尚未解锁配方" }, materials_empty = { "Materials exhausted", "材料耗尽" },
    tool_missing = { "No usable tool in inventory", "库存没有可用工具" }, inventory_full = { "Inventory full", "背包已满" },
    timeout = { "No progress", "无进展" }, action_failed = { "Action failed", "动作失败" },
    location = { "Location", "位置" }, danger = { "Danger", "危险" }, resource = { "Resource", "资源" }, rally = { "Rally", "集合" },
    signal_fire = { "Signal fire", "信号火" },
    ping_kind = { "Alt + map click marker", "Alt＋地图点击标记" }, grid = { "Farm grid", "农田布点" },
    server_rule = { "Server rule · restart to change", "服务器规则 · 修改后重启" }, restricted = { "Disabled by server", "服务器未允许" },
    conflict = { "Overlapping mod enabled", "已启用重叠功能模组" },
    first_tip = { "Wildwise is ready. F7 opens settings. Shift-click queues actions.", "Wildwise 已就绪。F7 打开设置，Shift＋点击添加队列。" },
    unknown = { "Unavailable", "暂不可用" }, default = { "Default", "默认" }, rider = { "Rider", "行牛" },
    ornery = { "Ornery", "战牛" }, pudgy = { "Pudgy", "肥牛" },
    execute_plan = { "Execute plan", "执行布点" }, cancel_plan = { "Cancel preview", "取消预览" },
    enabled_points = { "Valid / total", "有效／总点数" }, menu_key = { "Menu key", "菜单按键" }, queue_key = { "Queue modifier", "队列修饰键" },
    beefalo_key = { "Beefalo toggle", "牛状态切换键" }, rebind = { "Press a key…", "请按键…" },
    beefalo_visible = { "Show beefalo status", "显示牛状态" }, beefalo_x = { "Beefalo horizontal offset", "牛状态水平偏移" },
    beefalo_y = { "Beefalo vertical offset", "牛状态垂直偏移" }, auto = { "Follow game", "跟随游戏" },
    zh = { "简体中文", "简体中文" }, en = { "English", "English" },
    recipes = { "Recipes using hovered food", "包含所选食材的料理" }, find = { "Locate same item", "定位同类物品" },
    recipe_query = { "Four-ingredient recipe query", "四格食材料理查询" }, four_ingredients = { "Choose four ingredients", "请选择四格食材" },
    invalid_ingredient = { "Not a cooking ingredient", "不是有效烹饪食材" }, query = { "Query recipes", "查询料理" },
    more = { "More", "更多" }, back = { "Back", "返回" }, language = { "Language", "语言" },
    combat = { "Combat", "战斗" }, food = { "Food", "食物" }, equipment = { "Equipment", "装备" },
    progress = { "Timers", "加工进度" }, farm = { "Farming", "农业" }, follower = { "Followers", "随从" },
    container = { "Storage", "容器" }, world = { "World", "世界" }, categories = { "Information categories", "信息类别" },
}
function M.language(setting, G)
    if setting ~= "auto" then return setting end
    local code = G.LOC and G.LOC.GetLocaleCode() or "en"
    return code:sub(1, 2) == "zh" and "zh" or "en"
end
function M.get(key, lang)
    local value = M.text[key]
    return value and value[lang == "zh" and 2 or 1] or tostring(key)
end
return M
